# Generated by Django 5.2.4 on 2025-07-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_name_teacher_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
