# Generated by Django 5.2.3 on 2025-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_id", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("birth_date", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=10
                    ),
                ),
            ],
        ),
    ]
